baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "fateme-alk shell"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"
    userName = "Faateme"
    pcName = "PC"
    workDir = "Home"
    profile = "profile.txt"

    stdoutDelay = 6
    commandDelay = 35

    description = """
    Hi, I am Fateme Aliakbari!
    Nice to meet you.
    """

    [Params.Tree]
    use = true
    files = [
        ["Git", "https://github.com/fateme-alk/Karyar-Git-Course"],
        ["Python", "https://github.com/fateme-alk/Python-Programming],
    ]
